### ISSUE TITLE
using webAPI instead of local storage to search words

### ISSUE THREAD

**Issue by AshishKingdom** [mohitchandak/Dictionary_App#3]
A webAPI can be implemented to search for the meaning of words instead of using local storage. The only con for this will be that app
will not be able to suggest "do you mean ..." to users because there is no way to query all possible words from webAPI

**Comment by AshishKingdom** [comment]
Please assign me this issue so that I can start working on it. :)

**Comment by mohitchandak** [comment]
Sorry Was busy in some other work so was not able to assigned you !
You can start working on it :)

**Comment by AshishKingdom** [comment]
sure!! :)

**Comment by AshishKingdom** [comment]
Hey! I have opened a pull request regarding this issue.
